version:  '3.3'

services:
  mysql:
    build: 
      context: ./bufsbus-mysql
      dockerfile: Dockerfile
    restart: always
    container_name: bufsbus-mysql
    environment:
      MYSQL_ROOT_PASSWORD: tempPass
      MYSQL_DATABASE: bufsbus
      TZ: 'Asia/Seoul'
      MYSQL_USER: bus_user
      MYSQL_PASSWORD: busTempPass
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    expose:
      - '3306'
  node:
    depends_on: 
      - mysql
    build:
      context: ./bufsbus-server
      dockerfile: Dockerfile
    restart: always
    container_name: bufsbus-server
    ports:
      - '80:3000'
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: bus_user
      MYSQL_PASSWORD: busTempPass
      MYSQL_DATABASE: bufsbus